[profile.default]
names = true
sizes = true
libs = ["node_modules", "lib"]
fs_permissions = [{ access = "read", path = "./config/"}]
solc_version = "0.8.19"

# Inherits the properties of the default profile
[profile.make]
test = "/dev/null/"
optimizer_runs = 200
via_ir = true

[fuzz]
runs = 32

[invariant]
runs = 4
depth = 64

[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
avalanche = "https://rpc.ankr.com/avalanche"
tenderly = "https://rpc.tenderly.co/fork/${TENDERLY_FORK_ID}"


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
