[profile.default]
names = true
sizes = true
libs = ["node_modules", "lib"]
fs_permissions = [{ access = "read", path = "./config/"}]

[fuzz]
runs = 8

[invariant]
runs = 4
depth = 32

[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
avalanche = "https://rpc.ankr.com/avalanche"


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
