name: Forge build
description: Compiles the contracts & checks for their size

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: yarn

    - name: Install Foundry
      uses: onbjerg/foundry-toolchain@v1
      with:
        version: nightly

    - name: Check contracts sizes
      run: make contracts
      shell: bash
