name: Pull request

on:
  pull_request:
    paths:
      - .github/actions/**
      - .github/workflows/**
      - lib/**
      - src/**
      - test/**
      - foundry.toml
      - remappings.txt

jobs:
  forge-fmt:
    name: Forge format

    uses: ./.github/workflows/forge-fmt.yml
    secrets: inherit
  test-ethereum-mainnet:
    if: github.head_ref != 'main' && github.head_ref != 'dev' # already triggered by push

    name: Forge tests

    uses: ./.github/workflows/forge-test.yml
    with:
      network: ethereum-mainnet
    secrets: inherit
