name: Pull request

on:
  pull_request:
    paths:
      - lib/**
      - src/**
      - test/**
      - foundry.toml
      - remappings.txt
      - .github/workflows/pull_request.yml

jobs:
  test-ethereum-mainnet:
    if: github.head_ref != 'main' && github.head_ref != 'dev' # already triggered by push

    name: Forge

    uses: ./.github/workflows/forge-test.yml
    with:
      network: ethereum-mainnet
    secrets: inherit
