name: Push

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  forge-ethereum-mainnet:
    name: Forge

    uses: ./.github/workflows/forge-test.yml
    with:
      internal-fuzz-runs: 64
      integration-fuzz-runs: 64
      invariant-depth: 512
    secrets: inherit
