name: Push

on:
  push:
    branches:
      - main
      - dev

jobs:
  forge-ethereum-mainnet:
    name: Forge

    uses: ./.github/workflows/forge-test.yml
    with:
      network: ethereum-mainnet
      internal-fuzz-runs: 128
      integration-fuzz-runs: 128
      invariant-depth: 1024
    secrets: inherit
